quarkus:
  snowflake:
    worker-id: ${SNOWFLAKE_WORKER_ID:1}

  banner:
    enabled: false

    log:
      console:
        format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
      level: INFO
      category:
        "org.control.library": DEBUG

  details:
    domain: "https://controllibrary.org"
    name: "Control Library"
    version: "1.2.0"
    environment: "${QUARKUS_PROFILE:dev}"
    contact-email: "admin@controllibrary.org"

  http:
    port: 8888
    cors:
      enabled: true
      origins: "${FRONT_URL:http://localhost:3000}"
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: "*"

    auth:
      permission:
        public:
          paths: /v1/auth/login, /v1/auth/register
          policy: permit
        authenticated:
          paths: /*
          policy: authenticated

  smallrye-jwt:
    secrets:
      enabled: true
    verify:
      key:
        format: BASE64
        value: "ODc0NTc2MzQ1NzczODQ2Nzg2MzU3NjM0NjU3MzQ2NTM3NDY1NjQzNTY0NjU3NjM0NTY0MzY1NzM0NjU3NjM0NTA2MTQ1NjczNDY1NzY0NTM1NDUyMzQ1NDQw"

  datasource:
    db-kind: mariadb

  hibernate-orm:
    database:
      generation: update

  native:
    enabled: true

security:
  jwt:
    secret: "43537645734657367566465943573465736r7463r7346563752460345734657"
    group: "USER"
    exp:
      token: 24
      refresh: 168
  password:
    argon:
      memory: 65536
      iterations: 3
      parallelism: 1

validation:
  email:
    notblank: "The library's email address cannot be empty."
    format: "The email format provided is invalid."
    size: "The email should be between 5 and 150 characters long."